name: LLVM Premerge Checks

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/premerge.yaml

jobs:
  premerge-checks-linux:
    if: github.repository_owner == 'llvm'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Build and Test
        run: |
          ${MODIFIED_FILES:=$(git diff --name-only HEAD~1...HEAD)}
          echo $MODIFIED_FILES
          modified_dirs=$(echo "$MODIFIED_FILES" | cut -d'/' -f1 | sort -u)
          echo "$modified_dirs" >&2

